# Generated by Django 5.2.4 on 2025-11-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0003_customuser_date_joined_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержденный'), ('cancelled', 'Отмененный'), ('completed', 'Завершенный')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
