# Generated by Django 5.2.4 on 2025-11-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержденный'), ('cancelled', 'Отмененный')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
